# Generated by Django 5.2.17 on 2026-09-24 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('normalized', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Нормализованное название')),
                ('dest_code', models.CharField(blank=True, default='', help_text='Внутренний dest-код Wildberries; пусто — глобальный поиск', max_length=32, verbose_name='dest-код WB')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('ozon', 'Ozon'), ('wildberries', 'Wildberries'), ('yandex_market', 'Яндекс.Маркет')], max_length=32, verbose_name='Маркетплейс')),
                ('external_id', models.CharField(max_length=255, verbose_name='Внешний id / query / путь')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['marketplace', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CollectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('ozon', 'Ozon'), ('wildberries', 'Wildberries'), ('yandex_market', 'Яндекс.Маркет')], max_length=32, verbose_name='Маркетплейс')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('completed', 'Завершён'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=16)),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего')),
                ('processed', models.PositiveIntegerField(default=0, verbose_name='Обработано')),
                ('found', models.PositiveIntegerField(default=0, verbose_name='Найдено')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='jobs', to='core.category')),
                ('cities', models.ManyToManyField(blank=True, related_name='jobs', to='core.city')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача сбора',
                'verbose_name_plural': 'Задачи сбора',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('ozon', 'Ozon'), ('wildberries', 'Wildberries'), ('yandex_market', 'Яндекс.Маркет')], db_index=True, max_length=32, verbose_name='Маркетплейс')),
                ('external_seller_id', models.CharField(max_length=128, verbose_name='Внешний id продавца')),
                ('seller_url', models.URLField(blank=True, default='', max_length=512, verbose_name='Страница продавца')),
                ('seller_url_normalized', models.CharField(blank=True, default='', editable=False, max_length=512)),
                ('name', models.CharField(blank=True, default='', max_length=512, verbose_name='Название продавца')),
                ('inn', models.CharField(blank=True, db_index=True, default='', max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, default='', max_length=15, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, default='', verbose_name='Юридический адрес')),
                ('rating', models.CharField(blank=True, default='', max_length=16, verbose_name='Рейтинг')),
                ('registered_at', models.DateField(blank=True, null=True, verbose_name='Дата регистрации на маркетплейсе')),
                ('website', models.URLField(blank=True, default='', max_length=512, verbose_name='Сайт')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='Raw payload')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('last_enriched_at', models.DateTimeField(blank=True, null=True, verbose_name='Обогащён DaData')),
                ('categories', models.ManyToManyField(blank=True, related_name='sellers', to='core.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='core.city')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Мобильный телефон'), ('city_phone', 'Городской телефон'), ('email', 'Email'), ('site', 'Сайт')], max_length=16, verbose_name='Тип')),
                ('value', models.CharField(max_length=512, verbose_name='Значение')),
                ('source', models.CharField(choices=[('marketplace', 'Маркетплейс'), ('dadata', 'DaData')], default='marketplace', max_length=16, verbose_name='Источник')),
                ('source_ref', models.CharField(blank=True, default='', max_length=255)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.seller')),
            ],
            options={
                'verbose_name': 'Контакт продавца',
                'verbose_name_plural': 'Контакты продавцов',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('marketplace', 'external_id'), name='uniq_category_per_marketplace'),
        ),
        migrations.AddConstraint(
            model_name='seller',
            constraint=models.UniqueConstraint(fields=('marketplace', 'external_seller_id'), name='uniq_seller_per_marketplace'),
        ),
        migrations.AddConstraint(
            model_name='sellercontact',
            constraint=models.UniqueConstraint(fields=('seller', 'type', 'value'), name='uniq_contact_per_seller'),
        ),
    ]
