# Generated by Django 5.2.17 on 2026-09-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_cities_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionjob',
            name='checkpoint',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='retry_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='source_status',
            field=models.CharField(db_index=True, default='queued', max_length=32),
        ),
        migrations.AlterField(
            model_name='collectionjob',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('paused', 'Приостановлен'), ('completed', 'Завершён'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=16),
        ),
        migrations.CreateModel(
            name='CollectionJobSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_seller_id', models.CharField(max_length=128)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('detail_status', models.CharField(db_index=True, default='pending', max_length=24)),
                ('detail_error', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sellers', to='core.collectionjob')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_links', to='core.seller')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'detail_status'], name='core_collec_job_id_53ba97_idx'), models.Index(fields=['external_seller_id'], name='core_collec_externa_c8923b_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'external_seller_id'), name='uniq_job_seller_ref')],
            },
        ),
    ]
