# Generated by Django 5.2.17 on 2026-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collectionjob_checkpoint_collectionjob_last_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('ozon', 'Ozon'), ('wildberries', 'Wildberries'), ('yandex_market', 'Яндекс.Маркет')], max_length=32, unique=True, verbose_name='Маркетплейс')),
                ('cookies', models.TextField(help_text='Строка Cookie-заголовка (name=value; name2=value2) или JSON-словарь', verbose_name='Cookies')),
                ('source', models.CharField(default='admin', max_length=16, verbose_name='Источник')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Заметка')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сессия маркетплейса',
                'verbose_name_plural': 'Сессии маркетплейсов',
            },
        ),
    ]
