# Generated by Django 5.2.17 on 2026-09-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marketplacesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionjob',
            name='max_sellers',
            field=models.PositiveIntegerField(default=100, help_text='Лимит уникальных продавцов для этого запуска (минимум 1).', verbose_name='Сколько собирать'),
        ),
    ]
